
ARCHS?=x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLAGS+=-mmacosx-version-min=10.9 -D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC
LDFLAGS+=-mmacosx-version-min=10.9 -shared -lc++ $(ARCHOPTS)

LD=clang++
CXX=clang++
