#-----------------------------------
# makefile.linux
# Linux-specific build configuration
#-----------------------------------

# uncomment to override where `make install` puts chugin (see also: makefile)
# CHUGIN_PATH=/usr/local/lib/chuck

# compiler flags
FLAGS=-D__LINUX_ALSA__ -D__PLATFORM_LINUX__ -I$(CK_SRC_PATH) -fPIC $(shell pkg-config --cflags sndfile)
# linker flags
LDFLAGS=-shared -lstdc++ $(shell pkg-config --libs sndfile)

# which C++ compiler to use
CXX=g++
# which linker to use
LD=gcc
