MSBUILD=msbuild.exe

ifneq (,$(CHUCK_DEBUG))
CONFIG=Debug
CHUG_BIN=Debug/NHHall.chug
else
CONFIG=Release
CHUG_BIN=Release/NHHall.chug
endif

default: $(CHUG_BIN)

$(CHUG_BIN):
	$(MSBUILD) /p:Configuration=$(CONFIG)

clean:
	$(MSBUILD) /p:Configuration=$(CONFIG) /t:Clean

