ARCHS?=i386 x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FRAMEWORKS=Cocoa Foundation

FLAGS+=-D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS)
LDFLAGS+=-shared -lstdc++ $(addprefix -framework ,$(FRAMEWORKS)) \
-ObjC $(ARCHOPTS) \
-Wl,-undefined,dynamic_lookup

LD=clang++
CXX=clang++
OBJCXX=clang++
