
CHUGIN_PATH=/usr/local/lib/chuck

FLAGS=-D__LINUX_ALSA__ -D__PLATFORM_LINUX__ -DLINK_PLATFORM_LINUX=1 -I$(ASIO_INCLUDES) -I$(LINK_INCLUDES) -I$(CK_SRC_PATH) -fPIC -fpermissive -Wno-multichar
LDFLAGS=-shared -lstdc++

LD=gcc
CXX=g++
