//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a Chugin boilerplate, generated by chugerate!
//-----------------------------------------------------------------------------

// this should align with the correct versions of these ChucK files
#include "chuck_dl.h"
#include "chuck_def.h"

// general includes
#include <stdio.h>
#include <limits.h>
#include <sys/time.h>
#include <stdlib.h>

// example of getter/setter
CK_DLL_SFUN(systime_systime)
{
    RETURN->v_int = time(NULL);
}

// example of getter/setter
CK_DLL_SFUN(systime_systimef)
{
    timeval tv;
    gettimeofday(&tv, NULL);
    
    RETURN->v_float = tv.tv_sec + tv.tv_usec/(1000000.0);
}


// query function: chuck calls this when loading the Chugin
// NOTE: developer will need to modify this function to
// add additional functions to this Chugin
CK_DLL_QUERY( SysTime )
{
    // hmm, don't change this...
    QUERY->setname(QUERY, "SysTime");
    
    // begin the class definition
    // can change the second argument to extend a different ChucK class
    QUERY->begin_class(QUERY, "SysTime", "Object");

    QUERY->add_sfun(QUERY, systime_systime, "int", "systime");
    
    QUERY->add_sfun(QUERY, systime_systimef, "float", "systimef");

    // end the class definition
    // IMPORTANT: this MUST be called!
    QUERY->end_class(QUERY);

    // wasn't that a breeze?
    return TRUE;
}


