# Build dexed with JUCE buidls

trigger:
- main

pr:
- main

jobs:

- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.14'
        isMac: True
      win:
        imageName: 'vs2017-win2016'
        isWindows: True
      lin:
        imageName: 'ubuntu-18.04'
        isLinux: True

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1

  - bash: |
      sudo locale-gen es_ES
      sudo locale-gen fr_FR
      sudo locale-gen ja_JP
      sudo locale-gen zh_CN
      sudo update-locale
    displayName: Install Locales on Linux
    condition: variables.isLinux

  - bash: |
      cmake -Bbuild
      cmake --build build --target run-all-tests
    displayName: Run tests with cmake
