//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a AZA.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:AZA.chug AZA-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:AZA.chug AZA-test.ck -v3`
//--------------------------------------------------------------------

// print
<<< "dac has", dac.channels(), "channels" >>>;

Noise n => Plateau plateau => dac;
// Noise n1 => plateau.chan(1);

<<< "plateau has", plateau.channels(), "channels" >>>;
<<< "noise has", n.channels(), "channels" >>>;

10::samp => now;
