
ARCHS?=x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLUIDSYNTH_PREFIX=/opt/local

FLAGS+=-mmacosx-version-min=10.5 -D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS) -I$(FLUIDSYNTH_PREFIX)/include
LDFLAGS+=-mmacosx-version-min=10.5 -shared -lstdc++ $(ARCHOPTS) -L$(FLUIDSYNTH_PREFIX)/lib

LD=clang++
CXX=clang++
