
ARCHS?=x86_64 arm64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLUIDSYNTH_PREFIX=/opt/local

FLAGS+=-mmacosx-version-min=10.9 -I$(CK_SRC_PATH) $(ARCHOPTS) -I$(FLUIDSYNTH_PREFIX)/include
LDFLAGS+=-mmacosx-version-min=10.9 -shared -lc++ $(ARCHOPTS) -L$(FLUIDSYNTH_PREFIX)/lib

LD=clang++
CXX=clang++
