//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "TimeOfDay", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (TimeOfDay.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a TimeOfDay-test.ck boilerplate ChucK program
//      to help test your chugin (see TimeOfDay-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "chugin.h"
#include <sys/time.h>

CK_DLL_INFO(TimeOfDay)
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo(QUERY, CHUGIN_INFO_CHUGIN_VERSION, "v1.0.0");
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo(QUERY, CHUGIN_INFO_AUTHORS, "Alex Han & Andrew Zhu");
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo(QUERY, CHUGIN_INFO_DESCRIPTION, "Get the time of day yo");
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo(QUERY, CHUGIN_INFO_URL, "");
    // (optional) contact email
    QUERY->setinfo(QUERY, CHUGIN_INFO_EMAIL, "");
}

CK_DLL_SFUN(get_time_of_day)
{
    // int gettimeofday(struct timeval *tv, struct timezone *tz);
    timeval tv = {};
    if (gettimeofday(&tv, NULL) != 0)
    {
        perror("gettimeofday failed: ");
    }

    // struct timeval {
    //     time_t      tv_sec;     /* seconds */
    //     suseconds_t tv_usec;    /* microseconds */
    // };
    printf("tv_sec: %ld, tv_usec %d\n", tv.tv_sec, tv.tv_usec);

    RETURN->v_float = tv.tv_sec + (tv.tv_usec / 1000000.0);
}

CK_DLL_QUERY(TimeOfDay)
{
    // generally, don't change this...
    QUERY->setname(QUERY, "TimeOfDay");

    QUERY->begin_class(QUERY, "TimeOfDay", "Object");

    QUERY->add_sfun(QUERY, get_time_of_day, "float", "inSeconds");

    QUERY->end_class(QUERY);

    return TRUE;
}
