
LLVM_LDFLAGS = $(shell llvm-config --ldflags --libs all)

FLAGS=-pthread -D__LINUX_ALSA__ -D__PLATFORM_LINUX__ -I$(CK_SRC_PATH) -fPIC

# Old version... (shared linking)
#LDFLAGS=-shared -lstdc++ -lfaust $(LLVM_LDFLAGS) -lz -ldl -ltinfo -lssl -lcrypto

LDFLAGS=-shared -lstdc++ -l:libfaust.a $(LLVM_LDFLAGS) -lz -ldl -ltinfo -lssl -lcrypto

LD=g++
CXX=g++
