
ARCHS?=arm64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLAGS+=-mmacosx-version-min=10.9 -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC -I/usr/local/include
LDFLAGS+=-mmacosx-version-min=10.9 -L/usr/local/lib -shared $(ARCHOPTS) -lfaust `llvm-config --ldflags --libs all` -lz -lcurses

LD=clang++
CXX=clang++
