
ARCHS?=x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLAGS+=-mmacosx-version-min=10.9 -D__MACOSX_CORE__ -DEXTERNAL_DEBUG_CALLBACK -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC -I/usr/local/include 
LDFLAGS+=-mmacosx-version-min=10.9 -L/usr/local/lib -L/opt/local/lib -shared -lstdc++ $(ARCHOPTS) -lfaust `llvm-config-mp-3.8 --ldflags --libs all` -lcrypto -lz -lcurses -lstdc++

LD=clang++
CXX=clang++
